@startuml
class Company {
- String name
+ <<Create>> Company()
+ <<Create>> Company(String)
+ String getName()
+ void setName(String)
+ int getNumberOfEmployees()
+ void hire(Person,double)
+ void dismiss(Person)
+ boolean employed(Person)
+ double payroll()
}
class Person {
- String name
- String surname
- double salary
+ <<Create>> Person()
+ <<Create>> Person(String,String)
+ <<Create>> Person(String,String,double,Company)
+ String getName()
+ void setName(String)
+ String getSurname()
+ void setSurname(String)
+ double getSalary()
+ Company getCompany()
+ void selfHire(Company,double)
+ void selfDismiss(Company)
}

Person "*" -- "0..1" Company
@enduml